project:
  type: website
  render: 
    - "!ohi-global/"
    - "!structure.qmd"
    - "*.qmd"
    - "*.png"
  output-dir: docs
  

website:
  favicon: media/favicon-ohi-test.png
  sidebar:
    title: "OHI Methods 2024"
    logo: media/OHI_Logo_Blue.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
        icon: house
        
      - href: OHI-theory.qmd
      # look up numbering
        text: 1. Theory of OHI
        
      - href: OHI-score-anatomy.qmd
        text: 2. Brief Anatomy of OHI Scores # currently still has "data inclusion, data gaps"
        
      - href: data-inclusion-gaps.qmd
        text: 3. Data Inclusion & Gaps # instead of in score anatomy?
        
      - href: regions.qmd
        text: 4. Regions 
      
      - href: models/models.qmd
        text: 5. Models
        # subsections: 
        # regional and global index scores
        # goal scores
        # likely future status dimensions
        
      - href: goals/goal-models-data.qmd
        text: 6. Goal Models and Data
        # has all 10 goals etc.
        
      - href: data-layers/Sanjdata-layer-descriptions.qmd
        text: 7. Description of Data Layers
        # 107 subsections :)
        
      - href: ohi-global/documents/OHI.bib
        text: References
        icon: book
        
        
  page-footer: 
    left: Learn more about the [Ocean Health Index](https://oceanhealthindex.org/){target=_blank}
    # and a general overview of the [methodology](https://oceanhealthindex.org/methodology/)
    right: Source code available on [{{< fa brands github title="the Github octocat" >}} GitHub](https://github.com/OHI-Science/ohi-methods/tree/main){target=_blank}
  # {{< fa icon-name title="descriptive text for accessibility" >}}  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



