project:
  type: website
  output-dir: docs

website:
  title: "ohi-methods"
  sidebar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: OHI-theory.qmd
      # look up numbering
        text: 1. Theory of OHI
        
      - href: OHI-score-anatomy.qmd
        text: 2. Brief Anatomy of OHI Scores # data inclusion, data gaps
        
      - href: regions.qmd
        text: 3. Regions
      
      - href: models/models.qmd
        text: 4. Models
        # subsections: 
        # regional and global index scores
        # goal scores
        # likely future status dimensions
        
      - href: goals/goal-models-data.qmd
        text: 5. Goal Models and Data
        # has all 10 goals etc.
        
      - href: data-layers/data-layer-descriptions.qmd
        text: 6. Description of Data Layers
        # 107 subsections :)
        
      - href: ohi-global/documents/OHI.bib
        text: References
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



