project:
  type: website
  output-dir: docs

website:
  sidebar:
    title: "OHI Methods 2024 (test)"
    logo: media/OHI-logo.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
        icon: house
      - about.qmd
      - href: OHI-theory.qmd
      # look up numbering
        text: 1. Theory of OHI
        
      - href: OHI-score-anatomy.qmd
        text: 2. Brief Anatomy of OHI Scores # data inclusion, data gaps
        
      - href: regions.qmd
        text: 3. Regions
      
      - href: models/models.qmd
        text: 4. Models
        # subsections: 
        # regional and global index scores
        # goal scores
        # likely future status dimensions
        
      - href: goals/goal-models-data.qmd
        text: 5. Goal Models and Data
        # has all 10 goals etc.
        
      - href: data-layers/data-layer-descriptions.qmd
        text: 6. Description of Data Layers
        # 107 subsections :)
        
      # - href: ohi-global/documents/OHI.bib
      #   text: References
        
        
  page-footer: 
    left: Learn more about the [Ocean Health Index](https://oceanhealthindex.org/){target=_blank}
    # and a general overview of the [methodology](https://oceanhealthindex.org/methodology/)
    right: Source code available on [{{< fa brands github title="the Github octocat" >}} Github](https://github.com/OHI-Science/ohi-methods/tree/main){target=_blank}
  # {{< fa icon-name title="descriptive text for accessibility" >}}  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



