---
title: "."
embed-resources: true
toc: false
format:
  html:
    title-block-banner: media/ohi_banner.png
    title-block-banner-color: "#E3F1F2"
    include-in-header:
      - text: |
          <style>
          .quarto-title-block .quarto-title-banner {
            background-position-y: center;
            height: 180px;
          }
          </style>
---

## {{< fa water title="water waves" >}} Ocean Health Index 2024: Methods

The global Ocean Health Index assesses ocean health for 220 coastal countries and territories and has been conducted every year starting in 2012. The Index describes how well we are sustainably managing 10 goals for ocean ecosystems which represent the full suite of benefits that people want and need from the ocean. These goals include: artisanal fishing opportunity, biodiversity, carbon storage, clean waters, coastal livelihoods and economies, coastal protection, food provision, natural products, sense of place, and tourism and recreation. Each goal is given a score ranging from 0 to 100, and the full suite of goal scores are then averaged to obtain an overall index score for each region.

For more information about the philosophy of the Ocean Health Index and model development see Halpern et al. (2012, 2015) and [OHI Global](http://ohi-science.org/ohi-global/){target=_blank}, which includes information about downloading global ocean health data.
